### ISSUE TITLE
InterfaceImplementationMissingError: Tried using ProgramRepositoryInterface but no implementation of that interface was found. Make sure an implementation is registered, e.g. via "context.programs = new MyProgramRepository();".

### ISSUE THREAD

**Issue by SethyArt** [metaplex-foundation/umi#102]
Hello im trying to usi UMI to interact with metaplex delegate option for create a functionality to lock NFT in holders wallet

this is my code

```javascript
const { createUmi } = require('@metaplex-foundation/umi');
const { delegateStandardV1 } = require('@metaplex-foundation/mpl-token-metadata');
const { Connection, Keypair, PublicKey } = require('@solana/web3.js');
const bs58 = require('bs58');
const { mplTokenMetadata } = require('@metaplex-foundation/mpl-token-metadata');
const { mplCandyMachine } = require('@metaplex-foundation/mpl-candy-machine');

const umi = createUmi('https://api.devnet.solana.com')

async function delegateNFT(mintAddress, delegateAddress, walletKeypair) {
    

    const delegateStandardV1Accounts = {
        mint: new PublicKey(mintAddress),
        delegate: new PublicKey(delegateAddress),
        tokenOwner: walletKeypair.publicKey,
        // Include other necessary accounts as required
    };
    
    const delegateStandardV1Args = {
        tokenStandard: 0,
        // Include other necessary arguments if required
    };

    const delegateTransactionBuilder = delegateStandardV1(umi, {
        ...delegateStandardV1Accounts,
        ...delegateStandardV1Args,
    });


    try {
        const delegateTransaction = await delegateTransactionBuilder.buildAndSign(walletKeypair);
        const delegateTxSignature = await delegateTransaction.sendAndConfirm(umi);
        console.log("Delegate Transaction Signature:", delegateTxSignature);
    } catch (error) {
        console.error('Error delegating NFT:', error);
    }
}
``` 

for some reason i keep receiving error this error

    throw new InterfaceImplementationMissingError.InterfaceImplementationMissingError('ProgramRepositoryInterface', 'programs');
          ^

InterfaceImplementationMissingError: Tried using ProgramRepositoryInterface but no implementation of that interface was found. Make sure an implementation is registered, e.g. via "context.programs = new MyProgramRepository();".

i already try to solve this by many different methods, but everytime i include the umi.program i start to receive this error

**Comment by lorisleiva** [comment]
Hi! You're using Umi without any plugins. You should download the default bundle to have everything included out-of-the-box:

```sh
npm install @metaplex-foundation/umi-bundle-defaults
```

Then import the `createUmi` helper from the bundle directly:

```ts
// Before
const { createUmi } = require('@metaplex-foundation/umi');

// After
const { createUmi } = require('@metaplex-foundation/umi-bundle-defaults');
```

[See documentation](https://github.com/metaplex-foundation/umi/blob/main/docs/installation.md#for-end-users).

**Comment by SethyArt** [comment]
thank you this helped me but i stumbled in to another problem, i change te import like you said but then is started to receive another error

bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
/Users/tiagohenriquecarvalho/node_modules/@metaplex-foundation/umi-program-repository/dist/cjs/createDefaultProgramRepository.cjs:38
    return cluster === '*' ? programs : programs.filter(program => program.isOnCluster(cluster));
                                                                           ^

TypeError: program.isOnCluster is not a function
    at /Users/tiagohenriquecarvalho/node_modules/@metaplex-foundation/umi-program-repository/dist/cjs/createDefaultProgramRepository.cjs:38:76
    at Array.filter (<anonymous>)
    at Object.all (/Users/tiagohenriquecarvalho/node_modules/@metaplex-foundation/umi-program-repository/dist/cjs/createDefaultProgramRepository.cjs:38:50)
    at delegateNFT (/Users/tiagohenriquecarvalho/Documents/umi/umiTeste.js:14:31)
    at Object.<anonymous> (/Users/tiagohenriquecarvalho/Documents/umi/umiTeste.js:50:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

    const umi = createUmi('https://api.devnet.solana.com')
    umi.programs.add('metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s', false);
    const test = umi.programs.all('all');
    console.log(test);
    

trying to include the metaplex program in the UMI

**Comment by lorisleiva** [comment]
That's because you're trying to use a plugin as a program.

```ts
// Before
const umi = createUmi('https://api.devnet.solana.com/');
const mplTokenMetadataProgram = mplTokenMetadata();
umi.programs.add(mplTokenMetadataProgram);
const test = umi.programs.all('all');

// After
const umi = createUmi('https://api.devnet.solana.com/').use(mplTokenMetadata());
```

[See documentation](https://developers.metaplex.com/token-metadata/getting-started/js).

**Comment by SethyArt** [comment]
it work, sorry for the dumb quewstions newbbie here trying to learn and i dont find this question anywhere.

can you help me with one more question? i keep receving the error Error: The provided signer is not required to sign this transaction.

but i already passe the token owener as a signer, update autority, account token, i dont know who should sign this transaction

async function delegateNFT(mintAddress, delegateAddress, walletKeypair) {
    
    const umi = createUmi('https://api.devnet.solana.com', 'confirmed').use(mplTokenMetadata());
    const test = umi.programs.all('all');
    const myKeypairSigner = createSignerFromKeypair(umi, walletKeypair);
    umi.use(signerIdentity(myKeypairSigner));
    console.log(test);
    
    const delegateStandardV1Accounts = {
        mint: new PublicKey(mintAddress), // Mint address of the NFT
        delegate: new PublicKey(delegateAddress), // Account being delegated to
        tokenOwner: walletKeypair.publicKey, // Current owner's public key
        
        // Include other necessary accounts as required
    };
    
    const delegateStandardV1Args = {
        tokenStandard: 0,
        // Include other necessary arguments if required
    };

    const delegateTransactionBuilder = delegateStandardV1(umi, {
        ...delegateStandardV1Accounts,
        ...delegateStandardV1Args,
    });

    const transaction = await delegateTransactionBuilder.setLatestBlockhash(umi);

    try {
        const delegateTransaction = await transaction.buildAndSign(umi);
        const delegateTxSignature = await delegateTransaction.sendAndConfirm(umi);
        console.log("Delegate Transaction Signature:", delegateTxSignature);
    } catch (error) {
        console.error('Error delegating NFT:', error);
    }
    
    and i dont find it anywhere

**Comment by lorisleiva** [comment]
I think there's a fundamental misunderstanding on how to use Umi since you're trying to use `new PublicKey()` which is a legacy web3.js class and not a Umi type.

I recommend checking out the [Umi documentation](https://github.com/metaplex-foundation/umi/blob/main/docs/publickeys-signers.md) to understand more about the framework.
