### ISSUE TITLE
Error "The provided signer is not required to sign this transaction." will be thrown due to bad equality check

### ISSUE THREAD

**Issue by 4lve** [metaplex-foundation/umi#111]
From src/Transaction.ts

```typescript
const maxSigners = transaction.message.header.numRequiredSignatures;
  const signerPublicKeys = transaction.message.accounts.slice(0, maxSigners);
  const signerIndex = signerPublicKeys.findIndex(
    (key) => key === signerPublicKey
  );

  if (signerIndex < 0) {
    throw new Error(
      'The provided signer is not required to sign this transaction.'
    );
  }
```

Taking a look at the findIndex, in my testing the signerPublicKeys consists of strings while the signerPublicKey is a publicKey object. Therefore when doing an equality check it will always return false, to fix this we need to add `.toString()` on the methods

```typescript
const signerIndex = signerPublicKeys.findIndex(
    (key) => key.toString() === signerPublicKey.toString()
  );
```

**Comment by lorisleiva** [comment]
Hi there, I'm confused about this issue. In Umi, `PublicKeys` are simple `strings`. Therefore this equality checks should always work. Are you perhaps feeding Umi with legacy web3.js `PublicKey` classes?

**Comment by 4lve** [comment]
Oh, that could be the issue, didn't find a native key pair type

**Comment by lorisleiva** [comment]
Is this what you are looking for?

https://github.com/metaplex-foundation/umi/blob/main/docs/publickeys-signers.md#keypairs

**Comment by 4lve** [comment]
Oh, thanks
