### ISSUE TITLE
Question about metaplex implementation 

### ISSUE THREAD

**Issue by nicholasoxford** [metaplex-foundation/umi#30]
I am using this project for a cloudflare edge workload, and loving it! I was wondering if there are plans to decode NFTs with this package. In my experience you need a fully node compatible server to using the metaplex package, and it bloats the node modules.

**Comment by lorisleiva** [comment]
Hey, glad you're enjoying it! I'm in the process of documenting everything but yes there is a Umi-compatible library for token metadata available on the `alpha` tag of `@metaplex-foundation/mpl-token-metadata`. See https://github.com/metaplex-foundation/mpl-token-metadata.

**Comment by nicholasoxford** [comment]
Thank you! Decode data at the edge using mpl-token-metadata/apha. Insane! Thank you!

**Comment by lorisleiva** [comment]
Thanks! Btw, feel free to check my progress on the Umi documentation on this branch if that helps.

https://github.com/metaplex-foundation/umi/tree/loris/documentation/docs
