### ISSUE TITLE
Allow optional properties in structs

### ISSUE THREAD

**Issue by steveluscher** [metaplex-foundation/umi#72]
This is a bit of a fine point, but it would be nice to allow truly optional properties in structs.

# Problem

```ts
const serializer = struct([
    [
        'arrayOfNumbers',
        mapSerializer(
            array(u8(), { size: shortU16() }),
            // If `arrayOfNumbers` is absent in the source object, default to an empty array.
            (value: number[] | undefined) => value ?? [],
            // No way to express ‘exclude this property if empty’
            (value: number[]) => (value.length ? value : undefined) 
        ),
    ],
]);
```

# Actual

I'd like this to produce an object _without_ an `arrayOfNumbers` property, but this API can only be used to make it present-but-undefined.

```ts
serializer.deserialize(new Uint8Array([0])); // Returns `{"arrayOfNumbers": undefined}`
```

# Expectation

```ts
serializer.deserialize(new Uint8Array([0])); // Should return `{}`
```

**Comment by lorisleiva** [comment]
Hey! You can achieve that using the `mapSerializer` function on layer above ([Stackblitz](https://stackblitz.com/edit/umi-template?file=index.ts)).


```ts
const serializer = mapSerializer(
  struct([['arrayOfNumbers', array(u8(), { size: shortU16() })]]),
  (value: { arrayOfNumbers?: number[] }) => ({
    arrayOfNumbers: value.arrayOfNumbers ?? [],
  }),
  (value: { arrayOfNumbers: number[] }) =>
    value.arrayOfNumbers.length ? value : {}
);
```

**Comment by steveluscher** [comment]
![matt-leblanc-matt](https://github.com/metaplex-foundation/umi/assets/13243/25a1c54a-063e-4911-a134-fd0dc328e3c3)

**Comment by steveluscher** [comment]
![joey-friends](https://github.com/metaplex-foundation/umi/assets/13243/1c4ea7a4-26e2-401b-ac2b-5f7de22b2787)
